### ISSUE TITLE
KeyValidatorTrait

### ISSUE THREAD

**Issue by arnaspet** [chadicus/psr-cache-helper#3]
Is there a particular reason why this trait exists at all ?

To be exact, redis keys are usually stored like so: `namespace:value:id`. but validation gives me errors.

**Comment by chadicus** [comment]
I created the trait in order to enforce the key constraints with the [PSR-16](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-16-simple-cache.md#12-definitions) requirements. 
Particularly 
>  The following characters are reserved for future extensions and MUST NOT be supported by implementing libraries: {}()/\@:

**Comment by arnaspet** [comment]
Thanks for info!
